
services:
  postgres:
    image: postgres:15
    container_name: ledger-postgres
    environment:
      POSTGRES_DB: ledgerdb
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger123
    ports:
      - "5432:5432"
    volumes:
      - ledger_data:/var/lib/postgresql/data

volumes:
  ledger_data:
